// Slug parity guard.
//
// The slug algorithm in src/lib/slug.ts must produce the exact slugs the live
// site already has — changing them moves every content URL. This script
// asserts known input→slug pairs (sampled from production) and, when given a
// live sitemap URL, verifies every live content URL is still generated by a
// build in dist/.
//
// Usage:
//   node scripts/slug-parity.mjs                 # algorithm assertions only
//   node scripts/slug-parity.mjs --live          # + diff dist/ vs live sitemap

import { readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const SITE = "https://www.aalumvej26.dk";

// Inline copy of the algorithm under test (dist import of TS isn't available
// in a plain node script); must match src/lib/slug.ts byte-for-byte.
function slugify(s) {
  const out = String(s ?? "")
    .toLowerCase()
    .replace(/æ/g, "ae").replace(/ø/g, "oe").replace(/å/g, "aa")
    .replace(/ä/g, "ae").replace(/ö/g, "oe").replace(/ü/g, "ue").replace(/ß/g, "ss")
    .normalize("NFKD").replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60);
  return out.replace(/-+$/, "");
}

// Verify the inline copy matches the shipped source, so this guard can't
// silently drift from the real implementation.
const shipped = readFileSync(join(ROOT, "src/lib/slug.ts"), "utf8");
for (const fragment of [
  '.replace(/æ/g, "ae")',
  '.replace(/ß/g, "ss")',
  '.normalize("NFKD")',
  '.replace(/[^a-z0-9]+/g, "-")',
  ".slice(0, 60)",
]) {
  if (!shipped.includes(fragment)) {
    console.error(`FAIL: src/lib/slug.ts no longer contains ${JSON.stringify(fragment)}`);
    process.exit(1);
  }
}

// Known production pairs (title → live slug).
const CASES = [
  ["Cold Hawaii Ultra: Trail- og ultraløb med mål i Agger", "cold-hawaii-ultra-trail-og-ultraloeb-med-maal-i-agger"],
  ["Østersafari i Limfjorden", "oestersafari-i-limfjorden"],
  ["Nationalpark Thy", "nationalpark-thy"],
  ["Cold Hawaii Surf Weekend", "cold-hawaii-surf-weekend"],
];

let failed = false;
for (const [input, expected] of CASES) {
  const got = slugify(input);
  if (got !== expected) {
    console.error(`FAIL: slugify(${JSON.stringify(input)}) = ${got}, expected ${expected}`);
    failed = true;
  }
}
if (failed) process.exit(1);
console.log(`[slug-parity] ${CASES.length} algorithm assertions OK`);

if (process.argv.includes("--live")) {
  const dist = join(ROOT, "dist");
  if (!existsSync(dist)) {
    console.error("FAIL: dist/ missing — run a build first");
    process.exit(1);
  }
  const xml = execSync(`curl -s ${SITE}/sitemap.xml`, { encoding: "utf8" });
  const liveUrls = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)]
    .map((m) => m[1])
    .filter((u) => /\/(oplevelser|omraadet)\/[^/]+\/$/.test(u) && !u.includes("/kategori/"));
  let missing = 0;
  for (const url of liveUrls) {
    const rel = url.replace(SITE, "").replace(/\/$/, "");
    if (!existsSync(join(dist, rel, "index.html"))) {
      console.error(`MISSING in dist: ${url}`);
      missing++;
    }
  }
  if (missing) {
    console.error(`FAIL: ${missing}/${liveUrls.length} live content URLs not reproduced`);
    process.exit(1);
  }
  console.log(`[slug-parity] all ${liveUrls.length} live content URLs reproduced in dist/`);
}
