"""Seed source registry — converted 1:1 from the legacy source_registry.py.

Used once: the pipeline auto-seeds DynamoDB SOURCE items when the registry is
empty. After that, the registry lives in DynamoDB and this file is history.
"""

SEED_SOURCES = [
    {"domain": "7770thy.dk", "name": "7770thy.dk", "url": "https://7770thy.dk/", "tier": 1, "type": "Community directory, events", "notes": "Landsbyklyngen. /find-alle/ for directory.", "status": "active"},
    {"domain": "aggerbio.dk", "name": "Agger Bio", "url": "https://www.aggerbio.dk/", "tier": 1, "type": "Cinema", "notes": "/upcomming_movies/ for schedule.", "status": "active"},
    {"domain": "aggerbooking.dk", "name": "Agger Booking events", "url": "https://aggerbooking.dk/oplevelser/det-sker/", "tier": 1, "type": "Events", "notes": "Heavy Agger, Lady Walk, Cold Hawaii Ultra.", "status": "active"},
    {"domain": "aggerdarling.dk", "name": "Agger Darling", "url": "https://www.aggerdarling.dk/", "tier": 1, "type": "Restaurant, concerts", "notes": "/menu for menu. Live music. Year-round.", "status": "active"},
    {"domain": "restaurant-tri.com", "name": "Restaurant Tri", "url": "https://www.restaurant-tri.com/", "tier": 1, "type": "Fine dining", "notes": "Michelin-starred. Check seasonal open/close.", "status": "active"},
    {"domain": "signalmasten-agger.dk", "name": "Signalmasten Agger", "url": "https://signalmasten-agger.dk/", "tier": 1, "type": "Restaurant", "notes": "Year-round.", "status": "active"},
    {"domain": "vesterhavshytten-agger.dk", "name": "Vesterhavshytten", "url": "https://www.vesterhavshytten-agger.dk/", "tier": 1, "type": "Grillbar", "notes": "Seasonal — verify open/closed.", "status": "active"},
    {"domain": "aggersurfandevents.com", "name": "Agger Surf & Events", "url": "https://www.aggersurfandevents.com/", "tier": 1, "type": "Surf, activities", "notes": "Surf school, SUP, bar. Seasonal.", "status": "active"},
    {"domain": "coldhawaiiwatersport.dk", "name": "Cold Hawaii Watersport", "url": "https://coldhawaiiwatersport.dk/", "tier": 1, "type": "Water activities", "notes": "RIB boats, seal/dolphin safaris.", "status": "active"},
    {"domain": "agger-baadelaug.dk", "name": "Agger Bådelaug", "url": "https://agger-baadelaug.dk/", "tier": 1, "type": "Community events", "notes": "De Sorte Huse: Krabbefest, Tørfiskedag.", "status": "active"},
    {"domain": "aggerferiehuse.dk", "name": "Agger Feriehuse", "url": "https://www.aggerferiehuse.dk/dk/kystbyen-agger", "tier": 1, "type": "Town overview", "notes": "Business listings.", "status": "active"},
    {"domain": "aggerglamping.dk", "name": "Agger Glamping", "url": "https://aggerglamping.dk/en/look-in-the-area/", "tier": 1, "type": "Area guide", "notes": "Curated local guide.", "status": "active"},
    {"domain": "aggerholidays.dk", "name": "Agger Holidays", "url": "https://aggerholidays.dk/", "tier": 1, "type": "Area tips", "notes": "/spisesteder and /en/agger-and-other-experiences-thy.", "status": "active"},
    {"domain": "thy360.dk", "name": "Thy360 calendar", "url": "https://www.thy360.dk/kalender", "tier": 2, "type": "Events", "notes": "Primary structured event source for Thy.", "status": "active"},
    {"domain": "kultunaut.dk", "name": "KultuNaut", "url": "https://www.kultunaut.dk/", "tier": 2, "type": "Events by venue", "notes": "Filter to 7770 area.", "status": "active"},
    {"domain": "nationalparkthy.dk", "name": "Nationalpark Thy news", "url": "https://nationalparkthy.dk/om-os/nyheder/", "tier": 2, "type": "Nature events", "notes": "Seasonal programs, guided tours.", "status": "active"},
    {"domain": "nationalparkbooking.dk", "name": "Nationalparkbooking", "url": "https://nationalparkbooking.dk/", "tier": 2, "type": "Bookable experiences", "notes": "Guided tours, lectures.", "status": "active"},
    {"domain": "visitthy.com", "name": "VisitThy events", "url": "https://www.visitthy.com/thy/experiences/events-thy", "tier": 2, "type": "Tourism events", "notes": "Official tourism portal.", "status": "active"},
    {"domain": "visitnordvestkysten.dk", "name": "VisitNordvestkysten", "url": "https://www.visitnordvestkysten.dk/", "tier": 2, "type": "Regional tourism", "notes": "Agger-specific pages exist.", "status": "active"},
    {"domain": "museumthy.dk", "name": "Museum Thy", "url": "https://museumthy.dk/", "tier": 2, "type": "Exhibitions", "notes": "Thisted Museum, Heltborg.", "status": "active"},
    {"domain": "kunsthalthy.dk", "name": "Kunsthal Thy", "url": "https://kunsthalthy.dk/", "tier": 2, "type": "Art exhibitions", "notes": "Open Fri–Sun.", "status": "active"},
    {"domain": "smkthy.dk", "name": "SMK Thy", "url": "https://www.smkthy.dk/", "tier": 2, "type": "Art exhibitions", "notes": "National art in Doverodde.", "status": "active"},
    {"domain": "filmklubben-thy.dk", "name": "Filmklubben Thy", "url": "https://filmklubben-thy.dk/", "tier": 2, "type": "Film screenings", "notes": "Art-house at Kino Thisted.", "status": "active"},
    {"domain": "kinothisted.dk", "name": "Kino Thisted", "url": "https://www.kinothisted.dk/", "tier": 2, "type": "Cinema", "notes": "/programbestil-billetter/ for schedule.", "status": "active"},
    {"domain": "thyultra.dk", "name": "Cold Hawaii Ultra", "url": "https://thyultra.dk/", "tier": 2, "type": "Trail race", "notes": "Finishes in Agger. September.", "status": "active"},
    {"domain": "thyboron-turist.dk", "name": "Thyborøn Turist", "url": "https://www.thyboron-turist.dk/", "tier": 2, "type": "Tourism portal", "notes": "Day trip via ferry ~15 min.", "status": "active"},
    {"domain": "jyllandsakvariet.dk", "name": "JyllandsAkvariet", "url": "https://jyllandsakvariet.dk/", "tier": 2, "type": "Aquarium", "notes": "Touch pools, safaris. Thyborøn.", "status": "active"},
    {"domain": "seawarmuseum.dk", "name": "Sea War Museum", "url": "https://www.seawarmuseum.dk/", "tier": 2, "type": "WW1 museum", "notes": "Thyborøn.", "status": "active"},
    {"domain": "bunkermuseumhanstholm.dk", "name": "Bunkermuseum", "url": "https://bunkermuseumhanstholm.dk/", "tier": 2, "type": "WW2 museum", "notes": "Hanstholm. Closed Nov–Mar.", "status": "active"},
    {"domain": "coldhawaiisurfcamp.com", "name": "Cold Hawaii Surf Camp", "url": "https://coldhawaiisurfcamp.com/", "tier": 2, "type": "Surf school", "notes": "Klitmøller.", "status": "active"},
    {"domain": "thy-whisky.dk", "name": "Thy Whisky", "url": "https://www.thy-whisky.dk/", "tier": 2, "type": "Distillery tours", "notes": "Near Agger.", "status": "active"},
    {"domain": "vesterhavscaminoen.dk", "name": "VesterhavsCaminoen", "url": "https://vesterhavscaminoen.dk/", "tier": 2, "type": "Walking holidays", "notes": "Thyborøn–Vestervig.", "status": "active"},
    {"domain": "visitmors.com", "name": "VisitMors", "url": "https://www.visitmors.com/", "tier": 3, "type": "Tourism", "notes": "Mors island. ~45 min.", "status": "active"},
    {"domain": "destinationlimfjorden.com", "name": "Destination Limfjorden", "url": "https://www.destinationlimfjorden.com/", "tier": 3, "type": "Tourism", "notes": "Skive, Struer, Morsø.", "status": "active"},
    {"domain": "jesperhus.dk", "name": "Jesperhus", "url": "https://www.jesperhus.dk/", "tier": 3, "type": "Family park", "notes": "Major family attraction on Mors.", "status": "active"},
    {"domain": "museummors.dk", "name": "Museum Mors", "url": "https://museummors.dk/", "tier": 3, "type": "Museums", "notes": "Dueholm Kloster, fossil hunts.", "status": "active"},
    {"domain": "skaldyrcenteret.dk", "name": "Dansk Skaldyrcenter", "url": "https://skaldyrcenteret.dk/", "tier": 3, "type": "Shellfish", "notes": "Nykøbing Mors.", "status": "active"},
    {"domain": "limfjordsmuseet.dk", "name": "Limfjordsmuseet", "url": "https://limfjordsmuseet.dk/", "tier": 3, "type": "Maritime museum", "notes": "Løgstør.", "status": "active"},
    {"domain": "bovbjergfyr.dk", "name": "Bovbjerg Fyr", "url": "https://bovbjergfyr.dk/", "tier": 3, "type": "Lighthouse, art", "notes": "~1 hr south.", "status": "active"},
    {"domain": "vores-thy.dk", "name": "Vores Thy", "url": "https://vores-thy.dk/", "tier": 4, "type": "Local news", "notes": "/artikler for latest.", "status": "active"},
    {"domain": "thisted.dk", "name": "Thisted Kommune", "url": "https://www.thisted.dk/nyheder", "tier": 4, "type": "Municipal", "notes": "Official announcements.", "status": "active"},
    {"domain": "agger-hotel.dk", "name": "Agger Badehotel", "url": "https://agger-hotel.dk", "tier": 1, "type": "closed business", "notes": "CLOSED — renovating.", "status": "closed"},
    {"domain": "agger-is-café", "name": "Agger Is-Café", "url": "", "tier": 1, "type": "closed business", "notes": "UNKNOWN — no web presence.", "status": "closed"},
    {"domain": "kystcentret-thyborøn", "name": "Kystcentret Thyborøn", "url": "", "tier": 1, "type": "closed business", "notes": "CLOSED INDEFINITELY.", "status": "closed"},
]
